views:
  - title: Main
    cards:
      - type: custom:apexcharts-card
        update_interval: 5sec
        stacked: true
        series:
          - entity: sensor.random_0_1000
            name: Sensor 1
            type: area
            curve: straight
            color: yellow
          - entity: sensor.random_0_1000
            name: Sensor 2
            type: area
        hours_to_show: 0.20
        cache: true
        layout: minimal
        header:
          show: false

      - type: custom:apexcharts-card
        stacked: true
        series:
          - entity: sensor.random_0_1000
            name: RAM Usage
            unit: Mb
            type: area
            curve: smooth
          - entity: sensor.random_0_1000
            name: Ram Free
            type: area
        hours_to_show: 0.20
        cache: true
        layout: minimal
        header:
          floating: true

      - type: custom:apexcharts-card
        stacked: false
        series:
          - entity: sensor.random_0_1000
            name: test1
            type: column
          - entity: sensor.random_0_1000
            name: test2
            type: column
        hours_to_show: 0.25
        cache: true
      - type: custom:apexcharts-card
        hours_to_show: 200
        series:
          - entity: sensor.humidity
            curve: straight

      - type: custom:apexcharts-card
        hours_to_show: 1
        header:
          show: false
        series:
          - entity: sensor.random0_100
            name: AVG
            curve: smooth
            type: line
            group_by:
              duration: 10min
              func: avg
          - entity: sensor.random0_100
            curve: smooth
            name: MIN
            type: line
            group_by:
              duration: 10min
              func: min
          - entity: sensor.random0_100
            curve: smooth
            name: MAX
            type: line
            group_by:
              duration: 10min
              func: max
          - entity: sensor.random0_100
            curve: smooth
            name: LAST
            type: line
            group_by:
              duration: 10min
              func: last
          - entity: sensor.random0_100
            curve: smooth
            name: FIRST
            type: line
            group_by:
              duration: 10min
              func: first

      - type: custom:apexcharts-card
        hours_to_show: 4
        series:
          - entity: sensor.humidity
            type: area
            name: Outside Humidity
            group_by:
              func: avg
              duration: 1h
          - entity: sensor.random0_100
            type: area
            name: Office Humidity
            group_by:
              func: avg
              duration: 1h

      - type: custom:apexcharts-card
        hours_to_show: 6
        header:
          show: false
        series:
          - entity: sensor.humidity
            type: line
            name: Outside Humidity
            group_by:
              func: avg
              duration: 30min
          - entity: sensor.random0_100
            type: column
            name: Office Humidity
            group_by:
              func: avg
              duration: 30min
