apexcharts_card_templates:
  test2:
    color_list:
      - red
      - red
  test:
    config_templates: test2
    graph_span: 24h
    color_list:
      - black
    all_series_config:
      group_by:
        duration: 1h
        func: avg
      stroke_width: 2

views:
  - title: Main
    panel: true
    cards:
      - type: grid
        columns: 3
        cards:
          - type: custom:apexcharts-card
            apex_config:
              chart:
                toolbar:
                  show: true
                  tools:
                    zoom: true
                    zoomin: true
                    zoomout: true
                    pan: true
                    reset: true
                zoom:
                  enabled: true
              fill:
                type: gradient
                gradient:
                  type: vertical
                  shadeIntensity: 0.8
                  stops:
                    - 0
                    - 1000
                  inverseColors: false
            update_interval: 5sec
            # stacked: true
            series:
              - entity: sensor.random_0_1000
                name: Sensor 1
                type: area
                curve: straight
                color: yellow
                show:
                  extremas: true
              - entity: sensor.random_0_1000
                name: Sensor 2
                type: area
                offset: -1d
                invert: true
            graph_span: 15min
            cache: true
            layout: minimal
            header:
              show: false

          - type: custom:apexcharts-card
            stacked: true
            span:
              offset: -1d
            series:
              - entity: sensor.random_0_1000
                name: RAM Usage
                unit: Mb
                type: area
                curve: smooth
              - entity: sensor.random_0_1000
                name: Ram Free
                type: area
                stroke_width: 20
            graph_span: 15min
            cache: true
            layout: minimal
            header:
              floating: true

          - type: custom:apexcharts-card
            update_interval: 2s
            stacked: true
            experimental:
              color_threshold: true
              hidden_by_default: true
              # disable_config_validation: true
            series:
              - entity: sensor.random_0_1000
                name: test1
                type: column
                show:
                  datalabels: true
                group_by:
                  duration: 1m
                  func: last
                transform: console.log(entity);  return x/10;
                color_threshold:
                  - value: 33
                    color: '#00ff00'
                  - value: 66
                    color: '#000001'
                  - value: 0
                    color: '#ff0000'

              - entity: sensor.random0_100
                name: test2
                type: column
                show:
                  hidden_by_default: true
                  datalabels: total
                group_by:
                  duration: 1m
                  func: last
                # color_threshold:
                #   - value: 0
                #     color: '#0000ff'
                #   - value: 33
                #     color: '#00ff00'
                #   - value: 66
                #     color: '#ff0000'
            graph_span: 10min
            cache: true
          - type: custom:apexcharts-card
            graph_span: 200h
            series:
              - entity: sensor.humidity
                curve: straight
                show:
                  extremas: true

          - type: custom:apexcharts-card
            graph_span: 1h
            header:
              title: Test Aggregate
              show: true
              show_states: true
              colorize_states: true
            series:
              - entity: sensor.random0_100
                name: AVG
                curve: smooth
                type: line
                show:
                  as_duration: millisecond
                  in_header: true
                  in_chart: false
                group_by:
                  duration: 10min
                  func: avg
              - entity: sensor.random0_100
                name: AVG
                curve: smooth
                type: line
                show:
                  as_duration: minute
                group_by:
                  duration: 10min
                  func: avg
              - entity: sensor.random0_100
                curve: smooth
                name: MIN
                type: line
                show:
                  as_duration: hour
                group_by:
                  duration: 10min
                  func: min
              - entity: sensor.random0_100
                curve: smooth
                name: MAX
                type: line
                show:
                  as_duration: day
                group_by:
                  duration: 10min
                  func: max
              - entity: sensor.random0_100
                curve: smooth
                name: LAST
                type: line
                show:
                  # as_duration: month
                  in_header: true
                  in_chart: false
                # show:
                #   as_duration: month
                group_by:
                  duration: 10min
                  func: last
              - entity: sensor.random0_100
                curve: smooth
                name: FIRST
                type: line
                show:
                  as_duration: year
                  in_header: raw
                group_by:
                  duration: 10min
                  func: first
              - entity: sensor.random0_100
                curve: smooth
                name: DIFF
                type: line
                show:
                  as_duration: year
                  in_header: true
                  in_chart: false
                group_by:
                  duration: 10min
                  func: diff

          - type: custom:apexcharts-card
            graph_span: 4h
            header:
              title: Test
            series:
              - entity: sensor.humidity
                type: area
                name: Outside Humidity
                opacity: 0.3
                group_by:
                  func: avg
                  duration: 1h
              - entity: sensor.random0_100
                type: area
                name: Office Humidity
                opacity: 0.3
                group_by:
                  func: avg
                  duration: 1h
                show:
                  datalabels: true
          - type: sensor
            entity: sensor.humidity
            graph: line

          - type: custom:apexcharts-card
            graph_span: 6h
            header:
              show: false
            series:
              - entity: sensor.humidity
                type: line
                name: Outside Humidity
                group_by:
                  func: avg
                  duration: 30min
              - entity: sensor.random0_100
                type: column
                name: Office Humidity
                group_by:
                  func: avg
                  duration: 30min
                # color_threshold:
                #   - value: 49
                #     color: '#ff0000'
                #   - value: 0
                #     color: '#00ff00'

          - type: custom:apexcharts-card
            header:
              show: true
              title: Start of day
            graph_span: 24h
            span:
              start: day
            series:
              - entity: sensor.random0_100
                extend_to_end: false
                type: column
                show:
                  datalabels: true
                group_by:
                  func: avg
                  fill: 'null'

          - type: custom:apexcharts-card
            header:
              show: true
              title: Last 8h
            graph_span: 8h
            span:
              end: hour
            apex_config:
              yaxis:
                - title:
                    text: test1
                  show: true
                  opposite: true
                  decimalsInFloat: 1
                - title:
                    text: Test2
                  show: true
                  # opposite: true
                  decimalsInFloat: 1
            series:
              - entity: sensor.random0_100
                extend_to_end: false
                type: column
                invert: true
                float_precision: 3
                group_by:
                  func: avg
                  fill: 'last'
                show:
                  legend_value: false
                  datalabels: true
              - entity: sensor.random0_100
                extend_to_end: false
                type: column
                group_by:
                  func: avg
                  fill: 'last'
                show:
                  datalabels: true
              - entity: sensor.random0_100
                extend_to_end: false
                type: column
                group_by:
                  func: avg
                  fill: 'last'
                show:
                  datalabels: true

          - type: custom:apexcharts-card
            span:
              start: day
            y_axis_precision: 5
            now:
              show: true
              color: '#ff0000'
              label: Now
            header:
              show: true
              show_states: true
            series:
              - entity: sensor.pvpc
                float_precision: 5
                show:
                  extremas: true
                data_generator: |
                  return [...Array(22).keys()].map((hour) => {
                    const attr = 'price_' + `${hour}`.padStart(2, '0') + 'h';
                    const value = entity.attributes[attr];
                    return [moment().startOf('day').hours(hour).valueOf(), value];
                  })

          - type: custom:apexcharts-card
            graph_span: 8d
            span:
              start: day
              offset: -3d
            header:
              show: true
              title: Temperature Forecast
              show_states: true
            now:
              show: true
              label: 'now'
              color: '#0066ff88'
            apex_config:
              legend:
                show: false
            series:
              - entity: weather.openweathermap
                name: Temperature
                unit: °C
                attribute: temperature
                fill_raw: last
                extend_to_end: false
                group_by:
                  func: avg
                  duration: 1h
              - entity: weather.openweathermap
                type: line
                extend_to_end: false
                unit: °C
                show:
                  in_header: false
                data_generator: |
                  return entity.attributes.forecast.map((entry) => {
                    return [new Date(entry.datetime).getTime(), entry.temperature];
                  });

          - type: custom:apexcharts-card
            graph_span: 20min
            experimental:
              color_threshold: true
            series:
              - entity: sensor.random_0_1000
                type: line
                stroke_width: 2
                color_threshold:
                  - value: 0
                    color: blue
                  - value: 250
                    color: green
                  - value: 500
                    color: yellow
                    # opacity: 0
                  - value: 500
                    color: orange
                  - value: 750
                    color: orange
                  - value: 750
                    color: red
                  - value: 1000
                    color: red
          - type: custom:apexcharts-card
            header:
              show: true
              title: radialBar
            chart_type: radialBar
            series:
              - entity: sensor.random0_100
              - entity: sensor.random_0_1000
                min: 0
                max: 1000
          - type: custom:apexcharts-card
            chart_type: pie
            header:
              show: true
              title: pie
            series:
              - entity: sensor.random0_100
              - entity: sensor.random_0_1000
          - type: custom:apexcharts-card
            chart_type: donut
            header:
              show: true
              title: donut
            series:
              - entity: sensor.random0_100
              - entity: sensor.random_0_1000
          - type: custom:apexcharts-card
            chart_type: line
            graph_span: 15m
            header:
              show: true
              title: line
            series:
              - entity: sensor.random0_100
                show:
                  extremas: true
                color_threshold:
                  - value: 0
                    color: '#0000ff'
                  - value: 33
                    color: '#00ff00'
                  - value: 66
                    color: '#ff0000'
              - entity: sensor.random_0_1000
                show:
                  extremas: true
          - type: custom:apexcharts-card
            header:
              show: true
              title: scatter
            chart_type: scatter
            apex_config:
              responsive:
                - breakpoint: 400
                  options:
                    chart:
                      height: 500px
                - breakpoint: 5000
                  options:
                    chart:
                      height: auto
            series:
              - entity: sensor.random0_100
                group_by:
                  func: sum
                  duration: 20min
              - entity: sensor.random_0_1000
                group_by:
                  func: sum
                  duration: 20min

          - type: custom:apexcharts-card
            graph_span: 1h
            update_delay: 5.5s
            # apex_config:
            #   dataLabels:
            #     enabled: true
            hours_12: true
            header:
              show: true
              title: Light Brightness (attribute test)
            series:
              - entity: light.kitchen_lights
                attribute: brightness
            apex_config:
              tooltip:
                x:
                  format: MMM

          - type: custom:apexcharts-card
            header:
              show: true
              title: shouldn't extend to end with group_by
            span:
              start: day
            series:
              - entity: sensor.random0_100
                group_by:
                  duration: 1h
                  func: last
              - entity: sensor.random0_100
                extend_to_end: false
                group_by:
                  duration: 1h
                  func: last

          - type: custom:apexcharts-card
            update_interval: 2s
            graph_span: 10s
            header:
              show: true
              title: should show a line
            series:
              - entity: sensor.outside_temperature
                curve: stepline
                extend_to_end: false

          - type: custom:apexcharts-card
            update_delay: 3s
            graph_span: 5min
            series:
              - entity: input_boolean.test_boolean
                transform: "return x === 'on' ? 1 : 0;"
          - type: custom:apexcharts-card
            update_delay: 3s
            graph_span: 5min
            series:
              - entity: input_boolean.test_boolean
                transform: "return x === 'on' ? 1 : 0;"
          - type: custom:apexcharts-card
            update_delay: 3s
            graph_span: 5min
            series:
              - entity: input_boolean.test_boolean
                transform: "return x === 'on' ? 1 : 0;"
          - type: custom:apexcharts-card
            graph_span: 30min
            experimental:
              color_threshold: true
            series:
              - entity: sensor.random0_100
                transform: return x / 2 - 15;
                color_threshold:
                  - value: -10
                    # color can be a color name, rgb(r, g, b), '#0000ff' or var(--color-variable)
                    # default is: the default color of the serie
                    color: blue
                    # optional opacity, value from 0 to 1.
                    # Default is 1 for 'type: line' and 0.7 for `type: area`
                    opacity: 0
                  - value: 0
                    color: cyan
                  - value: 15
                    color: green
                  - value: 25
                    color: orange
          - type: custom:apexcharts-card
            graph_span: 30min
            experimental:
              color_threshold: true
            series:
              - entity: sensor.random0_100
                type: area
                stroke_width: 0
                opacity: 0.5
                transform: return x / 2 - 15;
                invert: true
                color_threshold:
                  - value: -10
                    # color can be a color name, rgb(r, g, b), '#0000ff' or var(--color-variable)
                    # default is: the default color of the serie
                    # color: blue
                    # optional opacity, value from 0 to 1.
                    # Default is 1 for 'type: line' and 0.7 for `type: area`
                    # opacity: 1
                  - value: 0
                    color: cyan
                  - value: 15
                    color: green
                  - value: 25
                    color: orange
          - type: custom:apexcharts-card
            graph_span: 30min
            experimental:
              color_threshold: true
            series:
              - entity: sensor.random0_100
                type: column
                # stroke_width: 0
                transform: return x / 2 - 15;
                color_threshold:
                  - value: -10
                    # color can be a color name, rgb(r, g, b), '#0000ff' or var(--color-variable)
                    # default is: the default color of the serie
                    # color: blue
                    # optional opacity, value from 0 to 1.
                    # Default is 1 for 'type: line' and 0.7 for `type: area`
                    opacity: 0
                  - value: 0
                    color: cyan
                  - value: 15
                    color: green
                  - value: 25
                    color: orange

          - type: custom:apexcharts-card
            config_templates:
              - test
            series:
              - entity: sensor.temperature
              - entity: sensor.temperature
