views:
  - title: Main
    cards:
      - type: custom:apexcharts-card
        update_interval: 5sec
        stacked: true
        series:
          - entity: sensor.random_0_1000
            name: Sensor 1
            type: area
            curve: straight
            color: yellow
          - entity: sensor.random_0_1000
            name: Sensor 2
            type: area
        graph_span: 15min
        cache: true
        layout: minimal
        header:
          show: false

      - type: custom:apexcharts-card
        stacked: true
        series:
          - entity: sensor.random_0_1000
            name: RAM Usage
            unit: Mb
            type: area
            curve: smooth
          - entity: sensor.random_0_1000
            name: Ram Free
            type: area
        graph_span: 15min
        cache: true
        layout: minimal
        header:
          floating: true

      - type: custom:apexcharts-card
        stacked: false
        series:
          - entity: sensor.random_0_1000
            name: test1
            type: column
          - entity: sensor.random_0_1000
            name: test2
            type: column
        graph_span: 20min
        cache: true
      - type: custom:apexcharts-card
        graph_span: 200h
        series:
          - entity: sensor.humidity
            curve: straight

      - type: custom:apexcharts-card
        graph_span: 1h
        header:
          title: Test Aggregate
          show: true
          show_states: true
          colorize_states: true
        series:
          - entity: sensor.random0_100
            name: AVG
            curve: smooth
            type: line
            group_by:
              duration: 10min
              func: avg
          - entity: sensor.random0_100
            curve: smooth
            name: MIN
            type: line
            group_by:
              duration: 10min
              func: min
          - entity: sensor.random0_100
            curve: smooth
            name: MAX
            type: line
            group_by:
              duration: 10min
              func: max
          - entity: sensor.random0_100
            curve: smooth
            name: LAST
            type: line
            group_by:
              duration: 10min
              func: last
          - entity: sensor.random0_100
            curve: smooth
            name: FIRST
            type: line
            group_by:
              duration: 10min
              func: first

      - type: custom:apexcharts-card
        graph_span: 4h
        header:
          title: Test
        series:
          - entity: sensor.humidity
            type: area
            name: Outside Humidity
            group_by:
              func: avg
              duration: 1h
          - entity: sensor.random0_100
            type: area
            name: Office Humidity
            group_by:
              func: avg
              duration: 1h
      - type: sensor
        entity: sensor.humidity
        graph: line

      - type: custom:apexcharts-card
        graph_span: 6h
        header:
          show: false
        series:
          - entity: sensor.humidity
            type: line
            name: Outside Humidity
            group_by:
              func: avg
              duration: 30min
          - entity: sensor.random0_100
            type: column
            name: Office Humidity
            group_by:
              func: avg
              duration: 30min

      - type: custom:apexcharts-card
        header:
          show: true
          title: Start of day
        graph_span: 24h
        span:
          start: day
        apex_config:
          dataLabels:
            enabled: true
            dropShadow:
              enabled: true
        series:
          - entity: sensor.random0_100
            extend_to_end: false
            type: column
            group_by:
              func: avg
              fill: 'null'

      - type: custom:apexcharts-card
        header:
          show: true
          title: Last 8h
        graph_span: 8h
        span:
          end: hour
        apex_config:
          dataLabels:
            enabled: true
            dropShadow:
              enabled: true
        series:
          - entity: sensor.random0_100
            extend_to_end: false
            type: column
            invert: true
            group_by:
              func: avg
              fill: 'null'
          - entity: sensor.random0_100
            extend_to_end: false
            type: column
            group_by:
              func: avg
              fill: 'null'

      - type: custom:apexcharts-card
        span:
          start: day
        series:
          - entity: sensor.pvpc
            data_generator: |
              return [...Array(22).keys()].map((hour) => {
                const attr = 'price_' + `${hour}`.padStart(2, '0') + 'h';
                const value = entity.attributes[attr];
                return [moment().startOf('day').hours(hour).valueOf(), value];
              })
