/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ChartCardExternalConfig = t.iface([], {
  "type": t.lit('custom:apexcharts-card'),
  "chart_type": t.opt(t.union(t.lit('line'), t.lit('scatter'), t.lit('pie'), t.lit('donut'), t.lit('radialBar'))),
  "update_interval": t.opt("string"),
  "update_delay": t.opt("string"),
  "series": t.array("ChartCardSeriesExternalConfig"),
  "graph_span": t.opt("string"),
  "hours_12": t.opt("boolean"),
  "span": t.opt("ChartCardSpanExtConfig"),
  "y_axis_precision": t.opt("number"),
  "now": t.opt(t.iface([], {
    "show": t.opt("boolean"),
    "color": t.opt("string"),
    "label": t.opt("string"),
  })),
  "show": t.opt(t.iface([], {
    "loading": t.opt("boolean"),
  })),
  "cache": t.opt("boolean"),
  "stacked": t.opt("boolean"),
  "layout": t.opt("string"),
  "apex_config": t.opt("any"),
  "header": t.opt("ChartCardHeaderExternalConfig"),
  "style": t.opt("any"),
});

export const ChartCardSpanExtConfig = t.iface([], {
  "start": t.opt(t.union(t.lit('minute'), t.lit('hour'), t.lit('day'), t.lit('week'), t.lit('month'), t.lit('year'))),
  "end": t.opt(t.union(t.lit('minute'), t.lit('hour'), t.lit('day'), t.lit('week'), t.lit('month'), t.lit('year'))),
  "offset": t.opt("string"),
});

export const ChartCardSeriesExternalConfig = t.iface([], {
  "entity": "string",
  "attribute": t.opt("string"),
  "name": t.opt("string"),
  "type": t.opt(t.union(t.lit('line'), t.lit('column'), t.lit('area'))),
  "color": t.opt("string"),
  "curve": t.opt(t.union(t.lit('smooth'), t.lit('straight'), t.lit('stepline'))),
  "extend_to_end": t.opt("boolean"),
  "unit": t.opt("string"),
  "invert": t.opt("boolean"),
  "data_generator": t.opt("string"),
  "float_precision": t.opt("number"),
  "min": t.opt("number"),
  "max": t.opt("number"),
  "offset": t.opt("string"),
  "fill_raw": t.opt("GroupByFill"),
  "show": t.opt(t.iface([], {
    "as_duration": t.opt("ChartCardPrettyTime"),
    "legend_value": t.opt("boolean"),
    "in_header": t.opt("boolean"),
    "in_chart": t.opt("boolean"),
    "datalabels": t.opt("boolean"),
  })),
  "group_by": t.opt(t.iface([], {
    "duration": t.opt("string"),
    "func": t.opt("GroupByFunc"),
    "fill": t.opt("GroupByFill"),
  })),
  "transform": t.opt("string"),
  "color_threshold": t.opt(t.array("ChartCardColorThreshold")),
});

export const ChartCardPrettyTime = t.union(t.lit('millisecond'), t.lit('second'), t.lit('minute'), t.lit('hour'), t.lit('day'), t.lit('week'), t.lit('month'), t.lit('year'));

export const GroupByFill = t.union(t.lit('null'), t.lit('last'), t.lit('zero'));

export const GroupByFunc = t.union(t.lit('raw'), t.lit('avg'), t.lit('min'), t.lit('max'), t.lit('last'), t.lit('first'), t.lit('sum'), t.lit('median'), t.lit('delta'), t.lit('diff'));

export const ChartCardHeaderExternalConfig = t.iface([], {
  "show": t.opt("boolean"),
  "floating": t.opt("boolean"),
  "title": t.opt("string"),
  "show_states": t.opt("boolean"),
  "colorize_states": t.opt("boolean"),
});

export const ChartCardColorThreshold = t.iface([], {
  "value": "number",
  "color": "string",
  "opacity": t.opt("number"),
});

const exportedTypeSuite: t.ITypeSuite = {
  ChartCardExternalConfig,
  ChartCardSpanExtConfig,
  ChartCardSeriesExternalConfig,
  ChartCardPrettyTime,
  GroupByFill,
  GroupByFunc,
  ChartCardHeaderExternalConfig,
  ChartCardColorThreshold,
};
export default exportedTypeSuite;
