/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const ChartCardExternalConfig = t.iface([], {
  type: t.lit('custom:apexcharts-card'),
  series: t.array('ChartCardSeriesExternalConfig'),
  hours_to_show: t.opt('number'),
  cache: t.opt('boolean'),
  stacked: t.opt('boolean'),
  layout: t.opt('string'),
  apex_config: t.opt('any'),
  header: t.opt('ChartCardHeaderExternalConfig'),
});

export const ChartCardSeriesExternalConfig = t.iface([], {
  entity: 'string',
  name: t.opt('string'),
  type: t.opt(t.union(t.lit('line'), t.lit('bar'), t.lit('area'))),
  curve: t.opt(t.union(t.lit('smooth'), t.lit('straight'), t.lit('stepline'))),
  extend_to_end: t.opt('boolean'),
  unit: t.opt('string'),
});

export const ChartCardHeaderExternalConfig = t.iface([], {
  display: t.opt('boolean'),
});

const exportedTypeSuite: t.ITypeSuite = {
  ChartCardExternalConfig,
  ChartCardSeriesExternalConfig,
  ChartCardHeaderExternalConfig,
};
export default exportedTypeSuite;
